# Created with package:mono_repo v3.1.0-beta.1
name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  job_001:
    name: "OS: linux; SDK: dev; PKGS: _test_yaml, checked_yaml, json_annotation, json_serializable; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings --fatal-infos .`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_yaml checked_yaml json_annotation json_serializable
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartfmt dartanalyzer_0
  job_002:
    name: "OS: linux; SDK: dev; PKGS: _test_yaml, checked_yaml; TASKS: `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_yaml checked_yaml
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_0
  job_003:
    name: "OS: linux; SDK: dev; PKGS: _test_yaml, checked_yaml; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_yaml checked_yaml
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_1
  job_004:
    name: "OS: linux; SDK: 2.7.0; PKG: checked_yaml; TASKS: `dartanalyzer --fatal-warnings .`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: checked_yaml
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartanalyzer_1
  job_005:
    name: "OS: linux; SDK: 2.7.0; PKG: checked_yaml; TASKS: `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: checked_yaml
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_0
  job_006:
    name: "OS: linux; SDK: 2.7.0; PKG: checked_yaml; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: checked_yaml
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_1
  job_007:
    name: "OS: linux; SDK: dev; PKG: example; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings .`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: example
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartfmt dartanalyzer_1
